version: '3.8'

services:
  travel-agency-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
      - DATABASE_URL=jdbc:mysql://localhost:3306/happyghumakkads_travel?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Local MySQL for development
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: happyghumakkads_travel
      MYSQL_USER: travel_user
      MYSQL_PASSWORD: travel_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
