server:
  port: ${PORT:8080}

spring:
  application:
    name: happyghumakkads-travel-agency
  datasource:
    url: jdbc:postgresql://db.gbdwmrhdxhpfqmvcujgh.supabase.co:5432/postgres?sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory&user=postgres&password=Happyghum%401234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 10000
      max-lifetime: 300000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from-email: ${SENDGRID_FROM_EMAIL:info.happyghumakkads@gmail.com}
    from-name: ${SENDGRID_FROM_NAME:"Happy Ghumakkads"}

# Razorpay Configuration
razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}

# Logging - Production optimized
logging:
  level:
    com.happyghumakkads: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    root: INFO

# File Upload
spring.servlet.multipart:
  max-file-size: 10MB
  max-request-size: 10MB

# Database connection pool - Production optimized
spring.datasource.hikari:
  maximum-pool-size: 10
  minimum-idle: 5
  idle-timeout: 300000
  max-lifetime: 600000

# Brand metadata used in header/footer
brand:
  name: HappyGhumakkads
  logo-url: ${BRAND_LOGO_URL:/images/logo.svg}
  phone: "+91 84471 33338"
  email: info.happyghumakkads@gmail.com
  address: Mishra Complex, Ground Floor, Chauhan Nagar, Pateri, Satna (M.P.) 485001
  instagram: https://instagram.com/happyghumakkads/
  facebook: https://facebook.com/happyghumakkads/
